import { Inter } from 'next/font/google'
import './globals.css'

// COMPONENTS
import Header from '@/components/blocks/Header'
import Footer from '@/components/blocks/Footer.jsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
